server:
  port: 28090
grpc:
  port: 6565
  enableReflection: true
spring:
  application.name: test-app
management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  otlp.tracing.endpoint: http://jaeger-collector:4317
